import { Component } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { RouterLink } from '@angular/router';
import { HeaderComponent, ContactComponent } from './shared.component';

export const SERVICES = [{ slug: 'citi', title: 'C.I.T.I. · Centro de Innovación y Transferencia Industrial', text: 'Innovación, transferencia tecnológica y articulación con el sector industrial.', image: 'citi.png' }, { slug: 'certificacion-de-oficios', title: 'Certificación de oficios', text: 'Evaluación y certificación de competencias técnicas y profesionales.', image: 'certificacion-oficios.jpg' }, { slug: 'asesoramiento-tecnico', title: 'Asesoramiento técnico', text: 'Diagnósticos, orientación especializada y acompañamiento en proyectos.', image: 'asesoramiento-tecnico.jpg' }, { slug: 'auditorias-de-tanques', title: 'Auditorías de tanques', text: 'Inspecciones y evaluaciones técnicas para instalaciones industriales.', image: 'auditoria-tanques.jpg' }, { slug: 'capacitaciones-in-company', title: 'Capacitaciones In Company', text: 'Formación técnica diseñada para las necesidades de cada organización.', image: 'capacitacion-in-company.jpg' }, { slug: 'capacitaciones-abiertas', title: 'Capacitaciones abiertas', text: 'Cursos y jornadas para la comunidad y el sector productivo.', image: 'capacitaciones-abiertas.jpg' }, { slug: 'centro-de-soldadura', title: 'Centro de soldadura', text: 'Formación y servicios especializados en procesos de soldadura.', image: 'centro-soldadura.jpg' }, { slug: 'asistencia-tecnica', title: 'Asistencia técnica', text: 'Optimización de procesos, factibilidad e ingeniería aplicada.', image: '' }, { slug: 'investigacion-y-desarrollo', title: 'Investigación y Desarrollo', text: 'Nuevos productos, prototipos, validaciones e innovación de procesos.', image: '' }, { slug: 'laboratorios-y-ensayos', title: 'Laboratorios y Ensayos', text: 'Ensayos, mediciones, certificaciones y análisis especializados.', image: '' }, { slug: 'transformacion-digital', title: 'Transformación Digital', text: 'Industria 4.0, automatización, datos, IA y software.', image: '' }, { slug: 'financiamiento', title: 'Financiamiento', text: 'ANR, FONTAR, FONARSEC, créditos y formulación de proyectos.', image: '' }, { slug: 'capacitacion-in-company', title: 'Capacitación In Company', text: 'Cursos a medida, formación técnica y actualización profesional.', image: '' }];

@Component({ selector: 'utn-vinculacion', standalone: true, imports: [NgFor, NgIf, RouterLink, HeaderComponent, ContactComponent], template: `
<utn-header /><main class="page"><section class="hero"><p class="eyebrow">Soluciones para empresas, instituciones y organizaciones</p><h1>Innovación, formación y tecnología al servicio de tu negocio</h1><p>Conectamos organizaciones con conocimiento aplicado, asesoramiento técnico, capacitación y soluciones que impulsan productividad e innovación.</p></section><section class="content"><h2>Servicios y áreas de trabajo</h2><div class="service-grid"><a *ngFor="let service of services" [routerLink]="['/vinculacion', service.slug]" class="service-card"><img *ngIf="service.image" [src]="'/vinculacion/assets/' + service.image" [alt]="service.title"><h3>{{ service.title }}</h3><p>{{ service.text }}</p><span>Conocer servicio</span></a></div></section><utn-contact /></main>` })
export class VinculacionComponent { services = SERVICES; }